"""initial

Revision ID: 2329b33557bf
Revises: 
Create Date: 2026-04-30 19:07:15.918311
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

revision: str = '2329b33557bf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('workspace',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('global_canonical_concept',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('aliases', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'name')
    )
    op.create_index(op.f('ix_global_canonical_concept_workspace_id'), 'global_canonical_concept', ['workspace_id'], unique=False)
    op.create_table('global_canonical_entity',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('canonical_name', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('aliases', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'canonical_name', 'entity_type')
    )
    op.create_index(op.f('ix_global_canonical_entity_entity_type'), 'global_canonical_entity', ['entity_type'], unique=False)
    op.create_index(op.f('ix_global_canonical_entity_workspace_id'), 'global_canonical_entity', ['workspace_id'], unique=False)
    op.create_table('project',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('domain', sa.Text(), nullable=True),
    sa.Column('ontology_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('embedding_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('extraction_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('graph_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'workspace_id'),
    sa.UniqueConstraint('workspace_id', 'name')
    )
    op.create_index(op.f('ix_project_workspace_id'), 'project', ['workspace_id'], unique=False)
    op.create_table('cluster',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('algorithm', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cluster_algorithm'), 'cluster', ['algorithm'], unique=False)
    op.create_index(op.f('ix_cluster_project_id'), 'cluster', ['project_id'], unique=False)
    op.create_table('concept',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('aliases', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'project_id')
    )
    op.create_index(op.f('ix_concept_project_id'), 'concept', ['project_id'], unique=False)
    op.create_table('cross_project_link',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('source_project_id', sa.UUID(), nullable=False),
    sa.Column('target_project_id', sa.UUID(), nullable=False),
    sa.Column('source_ref_type', sa.Text(), nullable=False),
    sa.Column('source_ref_id', sa.UUID(), nullable=False),
    sa.Column('target_ref_type', sa.Text(), nullable=False),
    sa.Column('target_ref_id', sa.UUID(), nullable=False),
    sa.Column('link_type', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1'),
    sa.ForeignKeyConstraint(['source_project_id', 'workspace_id'], ['project.id', 'project.workspace_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_project_id', 'workspace_id'], ['project.id', 'project.workspace_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cross_project_link_link_type'), 'cross_project_link', ['link_type'], unique=False)
    op.create_index(op.f('ix_cross_project_link_source_project_id'), 'cross_project_link', ['source_project_id'], unique=False)
    op.create_index(op.f('ix_cross_project_link_source_ref_type'), 'cross_project_link', ['source_ref_type'], unique=False)
    op.create_index(op.f('ix_cross_project_link_target_project_id'), 'cross_project_link', ['target_project_id'], unique=False)
    op.create_index(op.f('ix_cross_project_link_target_ref_type'), 'cross_project_link', ['target_ref_type'], unique=False)
    op.create_index(op.f('ix_cross_project_link_workspace_id'), 'cross_project_link', ['workspace_id'], unique=False)
    op.create_table('document',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.Column('source_uri', sa.Text(), nullable=True),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('date', sa.Text(), nullable=True),
    sa.Column('tradition', sa.Text(), nullable=True),
    sa.Column('region', sa.Text(), nullable=True),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'ready', 'uploaded', 'parsing', 'parsed', 'chunking', 'chunked', 'embedding', 'embedded', 'extracting', 'graph_ready', 'failed', name='document_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'project_id')
    )
    op.create_index(op.f('ix_document_project_id'), 'document', ['project_id'], unique=False)
    op.create_index(op.f('ix_document_source_type'), 'document', ['source_type'], unique=False)
    op.create_index(op.f('ix_document_status'), 'document', ['status'], unique=False)
    op.create_table('entity',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('canonical_name', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('aliases', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'project_id')
    )
    op.create_index(op.f('ix_entity_entity_type'), 'entity', ['entity_type'], unique=False)
    op.create_index(op.f('ix_entity_project_id'), 'entity', ['project_id'], unique=False)
    op.create_table('graph_node',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('node_type', sa.Text(), nullable=False),
    sa.Column('ref_id', sa.UUID(), nullable=True),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'project_id')
    )
    op.create_index(op.f('ix_graph_node_node_type'), 'graph_node', ['node_type'], unique=False)
    op.create_index(op.f('ix_graph_node_project_id'), 'graph_node', ['project_id'], unique=False)
    op.create_index(op.f('ix_graph_node_ref_id'), 'graph_node', ['ref_id'], unique=False)
    op.create_table('research_note',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=True),
    sa.Column('chunk_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('graph_node_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_note_project_id'), 'research_note', ['project_id'], unique=False)
    op.create_table('chunk',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('citation', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('token_count >= 0'),
    sa.ForeignKeyConstraint(['document_id', 'project_id'], ['document.id', 'document.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index'),
    sa.UniqueConstraint('id', 'project_id')
    )
    op.create_index(op.f('ix_chunk_document_id'), 'chunk', ['document_id'], unique=False)
    op.create_index(op.f('ix_chunk_project_id'), 'chunk', ['project_id'], unique=False)
    op.create_table('processing_job',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('job_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'retrying', 'succeeded', 'failed', 'cancelled', name='processing_job_status'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_job_document_id'), 'processing_job', ['document_id'], unique=False)
    op.create_index(op.f('ix_processing_job_job_type'), 'processing_job', ['job_type'], unique=False)
    op.create_index(op.f('ix_processing_job_project_id'), 'processing_job', ['project_id'], unique=False)
    op.create_index(op.f('ix_processing_job_status'), 'processing_job', ['status'], unique=False)
    op.create_table('chunk_cluster',
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('cluster_id', sa.UUID(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1'),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunk.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cluster_id'], ['cluster.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chunk_id', 'cluster_id')
    )
    op.create_table('chunk_embedding',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunk.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chunk_id', 'provider', 'model')
    )
    op.create_index(op.f('ix_chunk_embedding_chunk_id'), 'chunk_embedding', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_chunk_embedding_model'), 'chunk_embedding', ['model'], unique=False)
    op.create_index(op.f('ix_chunk_embedding_provider'), 'chunk_embedding', ['provider'], unique=False)
    op.execute(
        "CREATE INDEX ix_chunk_embedding_embedding_ivfflat "
        "ON chunk_embedding USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100)"
    )
    op.create_table('claim',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('predicate', sa.Text(), nullable=False),
    sa.Column('object', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_text', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1'),
    sa.ForeignKeyConstraint(['chunk_id', 'project_id'], ['chunk.id', 'chunk.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'project_id')
    )
    op.create_index(op.f('ix_claim_chunk_id'), 'claim', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_claim_project_id'), 'claim', ['project_id'], unique=False)
    op.create_table('graph_edge',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('source_node_id', sa.UUID(), nullable=False),
    sa.Column('target_node_id', sa.UUID(), nullable=False),
    sa.Column('edge_type', sa.Text(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_chunk_id', sa.UUID(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1'),
    sa.CheckConstraint('source_node_id <> target_node_id'),
    sa.CheckConstraint('weight >= 0'),
    sa.ForeignKeyConstraint(['evidence_chunk_id', 'project_id'], ['chunk.id', 'chunk.project_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_node_id', 'project_id'], ['graph_node.id', 'graph_node.project_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_node_id', 'project_id'], ['graph_node.id', 'graph_node.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graph_edge_edge_type'), 'graph_edge', ['edge_type'], unique=False)
    op.create_index(op.f('ix_graph_edge_evidence_chunk_id'), 'graph_edge', ['evidence_chunk_id'], unique=False)
    op.create_index(op.f('ix_graph_edge_project_id'), 'graph_edge', ['project_id'], unique=False)
    op.create_index(op.f('ix_graph_edge_source_node_id'), 'graph_edge', ['source_node_id'], unique=False)
    op.create_index(op.f('ix_graph_edge_target_node_id'), 'graph_edge', ['target_node_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_graph_edge_target_node_id'), table_name='graph_edge')
    op.drop_index(op.f('ix_graph_edge_source_node_id'), table_name='graph_edge')
    op.drop_index(op.f('ix_graph_edge_project_id'), table_name='graph_edge')
    op.drop_index(op.f('ix_graph_edge_evidence_chunk_id'), table_name='graph_edge')
    op.drop_index(op.f('ix_graph_edge_edge_type'), table_name='graph_edge')
    op.drop_table('graph_edge')
    op.drop_index(op.f('ix_claim_project_id'), table_name='claim')
    op.drop_index(op.f('ix_claim_chunk_id'), table_name='claim')
    op.drop_table('claim')
    op.drop_index(op.f('ix_chunk_embedding_provider'), table_name='chunk_embedding')
    op.drop_index(op.f('ix_chunk_embedding_model'), table_name='chunk_embedding')
    op.drop_index(op.f('ix_chunk_embedding_chunk_id'), table_name='chunk_embedding')
    op.drop_index('ix_chunk_embedding_embedding_ivfflat', table_name='chunk_embedding')
    op.drop_table('chunk_embedding')
    op.drop_table('chunk_cluster')
    op.drop_index(op.f('ix_processing_job_status'), table_name='processing_job')
    op.drop_index(op.f('ix_processing_job_project_id'), table_name='processing_job')
    op.drop_index(op.f('ix_processing_job_job_type'), table_name='processing_job')
    op.drop_index(op.f('ix_processing_job_document_id'), table_name='processing_job')
    op.drop_table('processing_job')
    op.drop_index(op.f('ix_chunk_project_id'), table_name='chunk')
    op.drop_index(op.f('ix_chunk_document_id'), table_name='chunk')
    op.drop_table('chunk')
    op.drop_index(op.f('ix_research_note_project_id'), table_name='research_note')
    op.drop_table('research_note')
    op.drop_index(op.f('ix_graph_node_ref_id'), table_name='graph_node')
    op.drop_index(op.f('ix_graph_node_project_id'), table_name='graph_node')
    op.drop_index(op.f('ix_graph_node_node_type'), table_name='graph_node')
    op.drop_table('graph_node')
    op.drop_index(op.f('ix_entity_project_id'), table_name='entity')
    op.drop_index(op.f('ix_entity_entity_type'), table_name='entity')
    op.drop_table('entity')
    op.drop_index(op.f('ix_document_status'), table_name='document')
    op.drop_index(op.f('ix_document_source_type'), table_name='document')
    op.drop_index(op.f('ix_document_project_id'), table_name='document')
    op.drop_table('document')
    op.drop_index(op.f('ix_cross_project_link_workspace_id'), table_name='cross_project_link')
    op.drop_index(op.f('ix_cross_project_link_target_ref_type'), table_name='cross_project_link')
    op.drop_index(op.f('ix_cross_project_link_target_project_id'), table_name='cross_project_link')
    op.drop_index(op.f('ix_cross_project_link_source_ref_type'), table_name='cross_project_link')
    op.drop_index(op.f('ix_cross_project_link_source_project_id'), table_name='cross_project_link')
    op.drop_index(op.f('ix_cross_project_link_link_type'), table_name='cross_project_link')
    op.drop_table('cross_project_link')
    op.drop_index(op.f('ix_concept_project_id'), table_name='concept')
    op.drop_table('concept')
    op.drop_index(op.f('ix_cluster_project_id'), table_name='cluster')
    op.drop_index(op.f('ix_cluster_algorithm'), table_name='cluster')
    op.drop_table('cluster')
    op.drop_index(op.f('ix_project_workspace_id'), table_name='project')
    op.drop_table('project')
    op.drop_index(op.f('ix_global_canonical_entity_workspace_id'), table_name='global_canonical_entity')
    op.drop_index(op.f('ix_global_canonical_entity_entity_type'), table_name='global_canonical_entity')
    op.drop_table('global_canonical_entity')
    op.drop_index(op.f('ix_global_canonical_concept_workspace_id'), table_name='global_canonical_concept')
    op.drop_table('global_canonical_concept')
    op.drop_table('workspace')
    # ### end Alembic commands ###
